# Generated by Django 4.0.1 on 2022-02-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=55)),
                ('alley', models.CharField(max_length=3)),
                ('row', models.CharField(max_length=3)),
                ('column', models.CharField(max_length=3)),
                ('address', models.CharField(blank=True, max_length=25)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('is_disponible', models.BooleanField(default=False)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('sku', models.CharField(max_length=255, null=True, unique=True)),
                ('barcode', models.ImageField(null=True, upload_to='products/codes/')),
                ('unstored_items', models.PositiveIntegerField(null=True)),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.emplacement')),
            ],
        ),
    ]
