# Generated by Django 4.0.1 on 2022-02-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stored_items',
            field=models.IntegerField(null=True),
        ),
    ]
