# Generated by Django 4.0.1 on 2022-02-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_emplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unstored_items',
            field=models.IntegerField(null=True),
        ),
    ]
