# Generated by Django 4.0.1 on 2022-02-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_order_id_orderpickup_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='is_picked',
            field=models.BooleanField(default=False),
        ),
    ]
