# Generated by Django 4.0.1 on 2022-02-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('Created', 'Created'), ('Processing', 'Processing'), ('Reported', 'Reported'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('No answer', 'No answer'), ('Returned', 'Returned'), ('Out for delivery', 'Out for delivery')], default=''),
        ),
    ]
