# Generated by Django 4.0.1 on 2022-02-25 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0007_orderitems_is_assigned_orderitems_is_picked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='is_picked',
        ),
        migrations.AddField(
            model_name='order',
            name='picker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendeur', to=settings.AUTH_USER_MODEL),
        ),
    ]
